/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package synapselogic;

/**
 * Interfaz principal donde se acoplan los paneles de acción (PanelControl y
 * PanelEdicionYGuardado), el panel de resultados, el visualizador y otros elementos visuales.
 * @author Luis Velásquez
 */

import javax.swing.JOptionPane;


@SuppressWarnings("serial")
public class MainFrame extends javax.swing.JFrame {
    
    //Declaración del controlador encargado de ejecutar la lógica y las solicitudes del usuario
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());
    private SynapseLogicController controlador;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        
        this.controlador = new SynapseLogicController();

        panelControl1.setControlador(this.controlador);
        panelControl1.setPanelResultados(panelResultados1);
        panelControl1.setVisualizadorGrafo(visualizadorGrafoGraphStream1);

        panelEdicionYGuardado1.setControlador(this.controlador);
        panelEdicionYGuardado1.setPanelResultados(panelResultados1);
        panelEdicionYGuardado1.setVisualizadorGrafo(visualizadorGrafoGraphStream1);
    }
    
    //Inicialización del controlador y los paneles que controla, integrados en la interfaz principal
    public MainFrame(SynapseLogicController controlador) {
        initComponents();

        if (controlador == null) {
            this.controlador = new SynapseLogicController();
        } else {
            this.controlador = controlador;
        }

        panelControl1.setControlador(this.controlador);
        
        panelControl1.setPanelResultados(panelResultados1);
        panelControl1.setVisualizadorGrafo(visualizadorGrafoGraphStream1);
        panelEdicionYGuardado1.setControlador(this.controlador);
        panelEdicionYGuardado1.setPanelResultados(panelResultados1);
        panelEdicionYGuardado1.setVisualizadorGrafo(visualizadorGrafoGraphStream1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        panelPrincipal = new javax.swing.JPanel();
        panelControl1 = new synapselogic.PanelControl();
        panelResultados1 = new synapselogic.PanelResultados();
        visualizadorGrafoGraphStream1 = new synapselogic.VisualizadorGrafoGraphStream();
        jSeparator1 = new javax.swing.JSeparator();
        panelEdicionYGuardado1 = new synapselogic.PanelEdicionYGuardado();
        instrucciónVisualizador = new javax.swing.JLabel();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(33, 41, 36));
        setForeground(java.awt.Color.black);

        panelPrincipal.setBackground(new java.awt.Color(33, 41, 36));

        instrucciónVisualizador.setBackground(new java.awt.Color(153, 153, 153));
        instrucciónVisualizador.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        instrucciónVisualizador.setForeground(new java.awt.Color(255, 255, 255));
        instrucciónVisualizador.setText("Para mover el visualizador, haga clic sobre este y use las flechas del teclado");

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelControl1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addComponent(panelResultados1, javax.swing.GroupLayout.PREFERRED_SIZE, 847, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panelEdicionYGuardado1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(visualizadorGrafoGraphStream1, javax.swing.GroupLayout.PREFERRED_SIZE, 1052, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(329, 329, 329)
                        .addComponent(instrucciónVisualizador)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(visualizadorGrafoGraphStream1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(instrucciónVisualizador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelResultados1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelEdicionYGuardado1, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)))
                    .addComponent(panelControl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(127, Short.MAX_VALUE))
        );

        getContentPane().add(panelPrincipal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Punto de inicio del sistema.
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.util.logging.Logger.getLogger("org.graphstream").setLevel(java.util.logging.Level.OFF);
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel instrucciónVisualizador;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator1;
    private synapselogic.PanelControl panelControl1;
    private synapselogic.PanelEdicionYGuardado panelEdicionYGuardado1;
    private javax.swing.JPanel panelPrincipal;
    private synapselogic.PanelResultados panelResultados1;
    private synapselogic.VisualizadorGrafoGraphStream visualizadorGrafoGraphStream1;
    // End of variables declaration//GEN-END:variables
}
