/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package synapselogic;

/**
 * Clase encargada de gestionar las acciones relacionadas al guardado de archivos y edición
 * del grafo, además de una opción para salir del sistema.
 * @author Luis Velásquez
 */
@SuppressWarnings("serial")
public class PanelEdicionYGuardado extends javax.swing.JPanel {
    
    /**
     * Interconexión del panel de edición y guardado con el controlador, 
     * el panel de resultados (consola) y el visualizador de grafo.
     */
    private SynapseLogicController controlador;
    private PanelResultados panelResultados;
    private VisualizadorGrafoGraphStream visualizadorGrafo;
   
    //Setters encargados de conectar elementos del frontend con el backend
    public void setControlador(SynapseLogicController controlador) {
    this.controlador = controlador;
    }

    public void setPanelResultados(PanelResultados panelResultados) {
        this.panelResultados = panelResultados;
    }

    public void setVisualizadorGrafo(VisualizadorGrafoGraphStream visualizadorGrafo) {
        this.visualizadorGrafo = visualizadorGrafo;
    }
    /**
     * Creates new form ediciónYGuardado
     */
    public PanelEdicionYGuardado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        agregarNeurona = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        eliminarSinapsis = new javax.swing.JButton();
        agregarSinapsis = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        guardarRed = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        btnSalir = new javax.swing.JButton();

        setBackground(new java.awt.Color(33, 41, 36));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Edición y guardado", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        setForeground(new java.awt.Color(33, 41, 36));
        setPreferredSize(new java.awt.Dimension(200, 300));

        agregarNeurona.setBackground(new java.awt.Color(0, 68, 161));
        agregarNeurona.setForeground(new java.awt.Color(255, 255, 255));
        agregarNeurona.setText("Agregar neurona");
        agregarNeurona.setBorderPainted(false);
        agregarNeurona.addActionListener(this::agregarNeuronaActionPerformed);

        eliminarSinapsis.setBackground(new java.awt.Color(0, 68, 161));
        eliminarSinapsis.setForeground(new java.awt.Color(255, 255, 255));
        eliminarSinapsis.setText("Eliminar sinapsis");
        eliminarSinapsis.setBorderPainted(false);
        eliminarSinapsis.addActionListener(this::eliminarSinapsisActionPerformed);

        agregarSinapsis.setBackground(new java.awt.Color(0, 68, 161));
        agregarSinapsis.setForeground(new java.awt.Color(255, 255, 255));
        agregarSinapsis.setText("Agregar sinapsis");
        agregarSinapsis.setBorderPainted(false);
        agregarSinapsis.addActionListener(this::agregarSinapsisActionPerformed);

        guardarRed.setBackground(new java.awt.Color(0, 68, 161));
        guardarRed.setForeground(new java.awt.Color(255, 255, 255));
        guardarRed.setText("Guardar red sináptica");
        guardarRed.setBorderPainted(false);
        guardarRed.addActionListener(this::guardarRedActionPerformed);

        btnSalir.setBackground(new java.awt.Color(255, 83, 20));
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Salir del sistema");
        btnSalir.setBorderPainted(false);
        btnSalir.addActionListener(this::btnSalirActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator3)
                    .addComponent(btnSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(guardarRed, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                    .addComponent(eliminarSinapsis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(agregarSinapsis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(agregarNeurona, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(agregarNeurona)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(agregarSinapsis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eliminarSinapsis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(guardarRed)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalir)
                .addContainerGap(76, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void agregarNeuronaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarNeuronaActionPerformed
        // TODO add your handling code here:
        if (!controladorDisponible()) { //Evitar que el código se rompa si hay un error al cargar el controlador
            return;
        }

        String id = javax.swing.JOptionPane.showInputDialog(
                this,
                "Ingrese el ID de la nueva neurona:",
                "Agregar neurona",
                javax.swing.JOptionPane.QUESTION_MESSAGE
        );
        
        //Consideración de posibles casos de error
        if (id == null) { //No se introduce un ID
            return;
        }

        id = id.trim(); //Se eliminan los espacios al principio y al final del input 

        if (id.isEmpty()) { //Se muestra un mensaje de error alertando al usuario
            mostrarAdvertencia("El ID de la neurona no puede estar vacío.");
            return;
        }

        try {
            //Se guarda la respuesta del usuario y se procesa la solicitud
            String mensaje = controlador.agregarNeurona(id);
            actualizarDespuesDeCambio(mensaje);

            //Se informa al usuario del éxito de la operación
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    mensaje,
                    "Neurona agregada",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE
            );
        } catch (Exception e) { //Se informa al usuario sobre errores ocurridos
            mostrarError("Error al agregar neurona: " + e.getMessage());
        } 
    }//GEN-LAST:event_agregarNeuronaActionPerformed

    private void agregarSinapsisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarSinapsisActionPerformed
        // TODO add your handling code here:
        if (!controladorDisponible()) { //Evitar que el código se rompa si hay un error al cargar el controlador
            return;
        }
        
        //Creación de ventana temporal que solicita los datos necesarios para agregar una sinapsis 
        javax.swing.JTextField txtOrigen = new javax.swing.JTextField();
        javax.swing.JTextField txtDestino = new javax.swing.JTextField();
        javax.swing.JTextField txtDistancia = new javax.swing.JTextField();
        javax.swing.JTextField txtNeurotransmisor = new javax.swing.JTextField();
        javax.swing.JTextField txtK = new javax.swing.JTextField("1");

        javax.swing.JPanel panel = new javax.swing.JPanel(new java.awt.GridLayout(0, 1, 5, 5));

        panel.add(new javax.swing.JLabel("Neurona origen:"));
        panel.add(txtOrigen);

        panel.add(new javax.swing.JLabel("Neurona destino:"));
        panel.add(txtDestino);

        panel.add(new javax.swing.JLabel("Distancia sináptica:"));
        panel.add(txtDistancia);

        panel.add(new javax.swing.JLabel("ID neurotransmisor:"));
        panel.add(txtNeurotransmisor);

        panel.add(new javax.swing.JLabel("Coeficiente k (0 < k <= 1):"));
        panel.add(txtK);

        // Continuar o cancelar la creación de la sinapsis
        int opcion = javax.swing.JOptionPane.showConfirmDialog(
                this,
                panel,
                "Agregar sinapsis dirigida",
                javax.swing.JOptionPane.OK_CANCEL_OPTION,
                javax.swing.JOptionPane.PLAIN_MESSAGE
        );

        if (opcion != javax.swing.JOptionPane.OK_OPTION) {
            return;
        }
        
        //Optimización y prevención de errores en el procesamiento al usar .trim()
        String origen = txtOrigen.getText().trim();
        String destino = txtDestino.getText().trim();
        String neurotransmisor = txtNeurotransmisor.getText().trim();

        if (origen.isEmpty() || destino.isEmpty() || neurotransmisor.isEmpty()) {
            mostrarAdvertencia("Origen, destino y neurotransmisor son obligatorios.");
            return; //Se advierte al usuario si faltan datos
        }

        try {
            //Extracción del contenido introducido para ser enviado al controlador
            double distancia = convertirDouble(txtDistancia.getText(), "distancia");
            double k = convertirDouble(txtK.getText(), "k");

            //Se aplican los cambios
            String mensaje = controlador.agregarSinapsis(origen, destino, distancia, neurotransmisor, k);
            actualizarDespuesDeCambio(mensaje);

            //Se informa al usuario del éxito de la operación
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    mensaje,
                    "Sinapsis agregada",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE
            );
        
        //Posibles casos de error y su respectivo manejo
        } catch (NumberFormatException e) {
            mostrarError("Distancia y k deben ser valores numéricos válidos.");
        } catch (Exception e) {
            mostrarError("Error al agregar sinapsis: " + e.getMessage());
        }   
    }//GEN-LAST:event_agregarSinapsisActionPerformed

    private void eliminarSinapsisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarSinapsisActionPerformed
        // TODO add your handling code here:
        if (!controladorDisponible()) { //Evitar que el código se rompa si hay un error al cargar el controlador
            return;
        }

        // Creación de una ventana emergente que permite introducir datos necesarios para la operación
        javax.swing.JTextField txtOrigen = new javax.swing.JTextField();
        javax.swing.JTextField txtDestino = new javax.swing.JTextField();

        javax.swing.JPanel panel = new javax.swing.JPanel(new java.awt.GridLayout(0, 1, 5, 5));

        panel.add(new javax.swing.JLabel("Neurona origen:"));
        panel.add(txtOrigen);

        panel.add(new javax.swing.JLabel("Neurona destino:"));
        panel.add(txtDestino);

        //Continuar o cancelar la acción
        int opcion = javax.swing.JOptionPane.showConfirmDialog(
                this,
                panel,
                "Eliminar sinapsis dirigida",
                javax.swing.JOptionPane.OK_CANCEL_OPTION,
                javax.swing.JOptionPane.PLAIN_MESSAGE
        );

        if (opcion != javax.swing.JOptionPane.OK_OPTION) {
            return;
        }

        //Procesamiento de datos introducidos
        String origen = txtOrigen.getText().trim();
        String destino = txtDestino.getText().trim();

        if (origen.isEmpty() || destino.isEmpty()) {
            mostrarAdvertencia("Origen y destino son obligatorios.");
            return; //Se alerta al usuario por falta de datos
        }
        
        // Confirmación final para llevar a cabo la operación
        int confirmacion = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "¿Seguro que desea eliminar la sinapsis dirigida " + origen + " -> " + destino + "?",
                "Confirmar eliminación",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.WARNING_MESSAGE
        );

        if (confirmacion != javax.swing.JOptionPane.YES_OPTION) {
            return;
        }

        try {
            // Extraer los datos introducidos y enviarlos al controlador para ejecutar la acción
            String mensaje = controlador.eliminarSinapsis(origen, destino);
            actualizarDespuesDeCambio(mensaje);

            //Informe de éxito
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    mensaje,
                    "Sinapsis eliminada",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE
            );
        } catch (Exception e) { //Informe de error
            mostrarError("Error al eliminar sinapsis: " + e.getMessage());
        }
    }//GEN-LAST:event_eliminarSinapsisActionPerformed

    private void guardarRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarRedActionPerformed
        // TODO add your handling code here:
        if (!controladorDisponible()) { //Evitar que el código se rompa si el controlador no logra cargarse
            return;
        }
        
        /**
        * Creación de una ventana temporal con filtro de solo archivos CSV 
        * para guardar la red actual en un nuevo archivo dentro del ordenador.
        */
        
        javax.swing.JFileChooser selector = new javax.swing.JFileChooser();
        selector.setDialogTitle("Guardar red sináptica");
        selector.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Archivos CSV (*.csv)", "csv"));
        selector.setSelectedFile(new java.io.File("red_sinaptica_guardada.csv"));

        int opcion = selector.showSaveDialog(this);

        if (opcion != javax.swing.JFileChooser.APPROVE_OPTION) {
            return;
        }

        java.io.File archivo = selector.getSelectedFile();

        //Evaluar si el archivo ya existe y decidir si reemplazarlo o no
        if (archivo.exists()) {
            int reemplazar = javax.swing.JOptionPane.showConfirmDialog(
                    this,
                    "El archivo ya existe. ¿Desea reemplazarlo?",
                    "Confirmar guardado",
                    javax.swing.JOptionPane.YES_NO_OPTION,
                    javax.swing.JOptionPane.WARNING_MESSAGE
            );

            if (reemplazar != javax.swing.JOptionPane.YES_OPTION) {
                return; //No se reemplazó el archivo
            }
        }

        try {
            //Se envían los datos al controlador
            String mensaje = controlador.guardarRed(archivo);

            if (panelResultados != null) { //Se registra la operación en el panel de resultados
                panelResultados.registrarOperacionSistema(mensaje);
            }

            //Informe de éxito
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    mensaje,
                    "Red guardada",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE
            );
        } catch (Exception e) { //Informe de error
            mostrarError("Error al guardar la red: " + e.getMessage());
        }
    }//GEN-LAST:event_guardarRedActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        
        //Se desea salir pero hay cambios sin guardar en el sistema
        if (controlador != null && controlador.hayCambiosSinGuardar()) {
            int opcion = javax.swing.JOptionPane.showConfirmDialog(
                    this,
                    //El sistema pide confirmación al usuario
                    "Hay cambios sin guardar. ¿Desea salir de todas formas?",
                    "Confirmar salida",
                    javax.swing.JOptionPane.YES_NO_OPTION,
                    javax.swing.JOptionPane.WARNING_MESSAGE
            );

            if (opcion != javax.swing.JOptionPane.YES_OPTION) {
                return; 
            }
        } else {
            //No se han realizado cambios y el usuario desea salir del sistema
            int opcion = javax.swing.JOptionPane.showConfirmDialog(
                    this,
                    //Se pide confirmación al usuario
                    "¿Desea salir del sistema?",
                    "Confirmar salida",
                    javax.swing.JOptionPane.YES_NO_OPTION,
                    javax.swing.JOptionPane.QUESTION_MESSAGE
            );

            if (opcion != javax.swing.JOptionPane.YES_OPTION) {
                return;
            }
        }

        java.awt.Window ventana = javax.swing.SwingUtilities.getWindowAncestor(this);

        if (ventana != null) {
            ventana.dispose(); // Cierra la ventana de interfaz
        }

        System.exit(0); // Comando de terminación del programa.
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * Clases auxiliares para los botones creados.  
     */
    
    private boolean controladorDisponible() {
        if (controlador == null) {
            mostrarError("Error interno: el controlador no fue inicializado.");
            return false;
        }
        return true;
        }

    private void actualizarDespuesDeCambio(String mensaje) {
        if (panelResultados != null) {
            panelResultados.registrarOperacionSistema(mensaje);
        }

        if (visualizadorGrafo != null) {
            visualizadorGrafo.actualizarGrafo(controlador.getGrafo());
            }
        }

    private void mostrarAdvertencia(String mensaje) { 
        javax.swing.JOptionPane.showMessageDialog(
                this,
                mensaje,
                "Validación",
                javax.swing.JOptionPane.WARNING_MESSAGE
    );
}

    private void mostrarError(String mensaje) {
        if (panelResultados != null) {
            panelResultados.mostrarErrorValidacion(mensaje);
        }

        javax.swing.JOptionPane.showMessageDialog(
                this,
                mensaje,
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE
        );
    }

    //Conversión de ciertos datos introducidos al tipo double para ser procesados por el controlador
    private double convertirDouble(String texto, String campo) {
        if (texto == null || texto.trim().isEmpty()) {
            throw new NumberFormatException("El campo " + campo + " está vacío.");
        }

        return Double.parseDouble(texto.trim().replace(',', '.'));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarNeurona;
    private javax.swing.JButton agregarSinapsis;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton eliminarSinapsis;
    private javax.swing.JButton guardarRed;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
