/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package synapselogic;

/**
 * Clase encargada de almacenar y acoplar acciones en el sistema con
 * la interfaz principal (MainFrame)
 * @author Luis Velásquez
 */
@SuppressWarnings("serial")
public class PanelControl extends javax.swing.JPanel {
    
    /**
     * Interconexión del panel de control con el controlador, 
     * el panel de resultados (consola) y el visualizador de grafo.
     */
    private SynapseLogicController controlador;
    private PanelResultados panelResultados;
    private VisualizadorGrafoGraphStream visualizadorGrafo;
    
    /**
     * Creates new form PanelControl
     */
    public PanelControl() {
        initComponents();
    }
    
    //Inicialización del controlador
    public PanelControl(SynapseLogicController controlador) {
        this.controlador = controlador;
        initComponents();
    }
    
    //Setters encargados de conectar elementos del frontend con el backend
    public void setControlador(SynapseLogicController controlador) {
    this.controlador = controlador;
    }
    
    public void setPanelResultados(PanelResultados panelResultados) {
        this.panelResultados = panelResultados;
    }

    public void setVisualizadorGrafo(VisualizadorGrafoGraphStream visualizadorGrafo) {
        this.visualizadorGrafo = visualizadorGrafo;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCargarRed = new javax.swing.JButton();
        lblEstadoRed = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnCargarNeuro = new javax.swing.JButton();
        lblEstadoNeuro = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txtNeuronaFuente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnDFS = new javax.swing.JButton();
        btnBFS = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDijkstraOrigen = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDijkstraDestino = new javax.swing.JTextField();
        btnDijkstra = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        btnFatiga = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTraumatismo = new javax.swing.JTextField();
        btnTraumatismo = new javax.swing.JButton();

        setBackground(new java.awt.Color(33, 41, 36));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Panel de Control", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        setForeground(new java.awt.Color(33, 41, 36));
        setToolTipText("");
        setPreferredSize(new java.awt.Dimension(200, 300));

        btnCargarRed.setBackground(new java.awt.Color(0, 68, 161));
        btnCargarRed.setForeground(new java.awt.Color(255, 255, 255));
        btnCargarRed.setText("Cargar red sináptica");
        btnCargarRed.setBorderPainted(false);
        btnCargarRed.addActionListener(this::btnCargarRedActionPerformed);

        lblEstadoRed.setBackground(new java.awt.Color(153, 153, 153));
        lblEstadoRed.setForeground(new java.awt.Color(255, 255, 255));
        lblEstadoRed.setText("Estado: No cargada");

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Carga de archivos CSV");

        btnCargarNeuro.setBackground(new java.awt.Color(0, 68, 161));
        btnCargarNeuro.setForeground(new java.awt.Color(255, 255, 255));
        btnCargarNeuro.setText("Cargar neurotransmisores");
        btnCargarNeuro.setBorderPainted(false);
        btnCargarNeuro.addActionListener(this::btnCargarNeuroActionPerformed);

        lblEstadoNeuro.setBackground(new java.awt.Color(153, 153, 153));
        lblEstadoNeuro.setForeground(new java.awt.Color(255, 255, 255));
        lblEstadoNeuro.setText("Estado: No cargados");

        jLabel2.setBackground(new java.awt.Color(153, 153, 153));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Análisis de conectividad");

        txtNeuronaFuente.setBackground(new java.awt.Color(215, 215, 215));

        jLabel3.setBackground(new java.awt.Color(153, 153, 153));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Neurona fuente (ID)");

        btnDFS.setBackground(new java.awt.Color(0, 68, 161));
        btnDFS.setForeground(new java.awt.Color(255, 255, 255));
        btnDFS.setText("Ejecutar DFS (Profundidad)");
        btnDFS.setBorderPainted(false);
        btnDFS.addActionListener(this::btnDFSActionPerformed);

        btnBFS.setBackground(new java.awt.Color(0, 68, 161));
        btnBFS.setForeground(new java.awt.Color(255, 255, 255));
        btnBFS.setText("Ejecutar BFS (Anchura)");
        btnBFS.setBorderPainted(false);
        btnBFS.addActionListener(this::btnBFSActionPerformed);

        jLabel4.setBackground(new java.awt.Color(153, 153, 153));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ruta óptima (Dijkstra)");

        jLabel5.setBackground(new java.awt.Color(153, 153, 153));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Origen (ID)");

        txtDijkstraOrigen.setBackground(new java.awt.Color(215, 215, 215));

        jLabel6.setBackground(new java.awt.Color(153, 153, 153));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Destino (ID)");

        txtDijkstraDestino.setBackground(new java.awt.Color(215, 215, 215));

        btnDijkstra.setBackground(new java.awt.Color(0, 68, 161));
        btnDijkstra.setForeground(new java.awt.Color(255, 255, 255));
        btnDijkstra.setText("Calcular ruta más rápida");
        btnDijkstra.setBorderPainted(false);
        btnDijkstra.addActionListener(this::btnDijkstraActionPerformed);

        jLabel7.setBackground(new java.awt.Color(153, 153, 153));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Simulador de deterioro");

        btnFatiga.setBackground(new java.awt.Color(0, 68, 161));
        btnFatiga.setForeground(new java.awt.Color(255, 255, 255));
        btnFatiga.setText("Aplicar fatiga");
        btnFatiga.setBorderPainted(false);
        btnFatiga.addActionListener(this::btnFatigaActionPerformed);

        jLabel9.setBackground(new java.awt.Color(153, 153, 153));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Simulador de traumatismo");

        jLabel8.setBackground(new java.awt.Color(153, 153, 153));
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Neurona a eliminar (ID)");

        txtTraumatismo.setBackground(new java.awt.Color(215, 215, 215));

        btnTraumatismo.setBackground(new java.awt.Color(0, 68, 161));
        btnTraumatismo.setForeground(new java.awt.Color(255, 255, 255));
        btnTraumatismo.setText("Aplicar traumatismo");
        btnTraumatismo.setBorderPainted(false);
        btnTraumatismo.addActionListener(this::btnTraumatismoActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnBFS, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDFS, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNeuronaFuente, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDijkstraOrigen, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                                    .addComponent(txtDijkstraDestino)))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(btnDijkstra)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(btnFatiga, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnTraumatismo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTraumatismo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEstadoRed)
                            .addComponent(btnCargarRed, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCargarNeuro)
                            .addComponent(lblEstadoNeuro))))
                .addContainerGap(178, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCargarRed)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEstadoRed, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCargarNeuro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEstadoNeuro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNeuronaFuente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnBFS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDFS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDijkstraOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtDijkstraDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDijkstra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFatiga)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtTraumatismo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTraumatismo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCargarRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarRedActionPerformed
        // TODO add your handling code here:
        if (controlador == null) { //Evitar que el programa se rompa si no se inicializa el controlador
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Error interno: el controlador no fue inicializado.",
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        // En el caso de querer sustituir la red sináptica actual, se pide confirmación al usuario
        if (controlador.requiereConfirmacionParaNuevaRed()) {
            int opcion = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "Hay cambios sin guardar en la red actual. ¿Deseas cargar una nueva red y reemplazar los datos en memoria?",
                "Confirmar nueva carga",
                javax.swing.JOptionPane.YES_NO_OPTION
            );

            if (opcion != javax.swing.JOptionPane.YES_OPTION) {
                return;
            }
        }

        // Despliegue de un JFileChooser para elegir una red sináptica
        javax.swing.JFileChooser selectorArchivos = new javax.swing.JFileChooser();
        selectorArchivos.setDialogTitle("Seleccione el archivo CSV de la Red Sináptica");
        
        // Implementación de un filtro que solo permita elegir archivos CSV del ordenador
        javax.swing.filechooser.FileNameExtensionFilter filtroCSV =
            new javax.swing.filechooser.FileNameExtensionFilter("Archivos CSV (*.csv)", "csv");

        selectorArchivos.setFileFilter(filtroCSV);

        int respuesta = selectorArchivos.showOpenDialog(this);

        if (respuesta == javax.swing.JFileChooser.APPROVE_OPTION) {
            java.io.File archivoSeleccionado = selectorArchivos.getSelectedFile();

        try {
            // Se envían los datos de la operación al controlador
            String mensaje = controlador.cargarRed(archivoSeleccionado);

            // Cambio en el texto debajo del botón cargar red, confirmando que el archivo se haya cargado
            lblEstadoRed.setText("Estado: Cargada (" + archivoSeleccionado.getName() + ")");
            lblEstadoRed.setForeground(new java.awt.Color(0, 153, 0));

            // Envío de información al panel de resultados
            if (panelResultados != null) {
                panelResultados.registrarOperacionSistema(
                        "Red sináptica cargada exitosamente desde: " + archivoSeleccionado.getName()
                );

                panelResultados.mostrarReporteCarga(
                        "Reporte de carga de red",
                        controlador.getUltimoReporteCargaRed()
                );
            }   

            // Actualización del grafo visual
            if (visualizadorGrafo != null) {
                visualizadorGrafo.actualizarGrafo(controlador.getGrafo());
            }

            // Informe de éxito
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    mensaje,
                    "Carga exitosa",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE
            );

        } catch (Exception e) { // Informe de error
            lblEstadoRed.setText("Estado: Error al cargar");
            lblEstadoRed.setForeground(java.awt.Color.RED);
            // Se actualiza el texto debajo del botón a un mensaje de error de color rojo
            
            String mensajeError = "Error al cargar la red: " + e.getMessage();

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    mensajeError,
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );

            // Se registra en el panel de resultados
            if (panelResultados != null) {
                panelResultados.registrarOperacionSistema(mensajeError);

                panelResultados.mostrarReporteCarga(
                        "Reporte de error al cargar red",
                        controlador.getUltimoReporteCargaRed()
                );
            }
          }
        }
    }//GEN-LAST:event_btnCargarRedActionPerformed

    private void btnCargarNeuroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarNeuroActionPerformed
        // TODO add your handling code here:
        if (controlador == null) { // Evitar que se rompa el programa si no se inicializa el controlador
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Error interno: el controlador no fue inicializado.",
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        // Despliegue de un JFileChooser para cargar el archivo con los neurotransmisores
        javax.swing.JFileChooser selectorArchivos = new javax.swing.JFileChooser();
        selectorArchivos.setDialogTitle("Seleccione el archivo CSV de Neurotransmisores");

        // Filtro que solo permite elegir archivos CSV del ordenador
        javax.swing.filechooser.FileNameExtensionFilter filtroCSV =
            new javax.swing.filechooser.FileNameExtensionFilter("Archivos CSV (*.csv)", "csv");

        selectorArchivos.setFileFilter(filtroCSV);

        int respuesta = selectorArchivos.showOpenDialog(this);

        // Confirmación de cargado
        if (respuesta == javax.swing.JFileChooser.APPROVE_OPTION) {
            java.io.File archivoSeleccionado = selectorArchivos.getSelectedFile();

        try {
            // Envío de datos de la operación al controlador
            String mensaje = controlador.cargarDiccionario(archivoSeleccionado);

            lblEstadoNeuro.setText("Estado: Cargado (" + archivoSeleccionado.getName() + ")");
            lblEstadoNeuro.setForeground(new java.awt.Color(0, 153, 0));

            // Registro de la operación en el panel de resultados
            if (panelResultados != null) {
                panelResultados.registrarOperacionSistema(
                        "Diccionario de neurotransmisores cargado desde: " + archivoSeleccionado.getName()
                );

                // Informe de error
                panelResultados.mostrarReporteCarga(
                        "Reporte de carga de neurotransmisores",
                        controlador.getUltimoReporteCargaNeurotransmisores()
                );
            }

            // Informe de éxito
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    mensaje,
                    "Carga exitosa",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE
            );

        } catch (Exception e) { // Error al cargar el archivo CSV
            lblEstadoNeuro.setText("Estado: Error al cargar");
            lblEstadoNeuro.setForeground(java.awt.Color.RED); 
            // Se actualiza el texto debajo del botón a un mensaje de error de color rojo

            // Se informa al usuario
            String mensajeError = "Error al cargar neurotransmisores: " + e.getMessage();

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    mensajeError,
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );

            // Se registra el informe de error en el panel de resultados
            if (panelResultados != null) {
                panelResultados.registrarOperacionSistema(mensajeError);

                panelResultados.mostrarReporteCarga(
                        "Reporte de error al cargar neurotransmisores",
                        controlador.getUltimoReporteCargaNeurotransmisores()
                );
                }
              }
            }
    }//GEN-LAST:event_btnCargarNeuroActionPerformed

    private void btnBFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBFSActionPerformed
        // TODO add your handling code here:
        if (controlador == null) { // Evitar que el programa se rompa si no se inicializa el controlador
                javax.swing.JOptionPane.showMessageDialog( //Se informa al usuario
                    this, 
                    "Error interno: el controlador no fue inicializado.",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Optimización y prevención de errores en el procesamiento de datos al usar .trim()
            String fuente = txtNeuronaFuente.getText().trim();

            // Se alerta al usuario de la introducción de un dato inválido
            if (fuente.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Ingrese la neurona fuente para ejecutar BFS.", "Campo vacío", javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }

            try {
                
                // Envío de los datos de la operación al controlador
                ResultadoConectividad resultado = controlador.analizarBFS(fuente);

                // Mostrar resultados en el panel de resultados (consola)
                if (panelResultados != null) {
                    panelResultados.mostrarResultadosConectividad("BFS", resultado);
                }

                // Resaltar visualmente las zonas aisladas en el grafo
                if (visualizadorGrafo != null) {
                    visualizadorGrafo.resaltarZonasAisladas(resultado);
                }

                // Ventana emergente informativa
                String mensaje = """
                                 Algoritmo: BFS
                                 Neurona fuente: """ + fuente + "\n\n"
                        + "Neuronas alcanzables: " + resultado.getAlcanzables().tamano() + "\n"
                        + resultado.getAlcanzables().toString() + "\n\n"
                        + "Neuronas inalcanzables: " + resultado.getInalcanzables().tamano() + "\n"
                        + resultado.getInalcanzables().toString() + "\n\n"
                        + "Red fuertemente conexa: "
                        + (resultado.esFuertementeConexa() ? "Sí" : "No");

                javax.swing.JOptionPane.showMessageDialog(this, mensaje, "Resultado BFS", javax.swing.JOptionPane.INFORMATION_MESSAGE);

            } catch (Exception e) { // Atrapar casos de error e informar al usuario
                if (panelResultados != null) {
                    panelResultados.mostrarErrorValidacion("Error en BFS desde " + fuente + ": " + e.getMessage());
                }
                javax.swing.JOptionPane.showMessageDialog(this, "Error al ejecutar BFS: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_btnBFSActionPerformed

    private void btnDFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDFSActionPerformed
        // TODO add your handling code here:
        if (controlador == null) { //Evitar que el programa se rompa si no se inicializa el controlador
                javax.swing.JOptionPane.showMessageDialog(
                    this,
                    // Se informa al usuario
                    "Error interno: el controlador no fue inicializado.",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Se extraen los datos del TextField, aplicando .trim() al mismo tiempo
            String fuente = txtNeuronaFuente.getText().trim();

            // Se alerta al usuario de la introducción de datos inválidos
            if (fuente.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Ingrese la neurona fuente para ejecutar DFS.", "Campo vacío", javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }

            try {
                // Se envían los datos de la operación al controlador
                ResultadoConectividad resultado = controlador.analizarDFS(fuente);

                // Registro de la operación en el panel de resultados
                if (panelResultados != null) {
                    panelResultados.mostrarResultadosConectividad("DFS", resultado);
                }
                // Resaltar visualmente las zonas aisladas en el grafo
                if (visualizadorGrafo != null) {
                    visualizadorGrafo.resaltarZonasAisladas(resultado);
                }

                // Ventana emergente informativa
                String mensaje = """
                                 Algoritmo: DFS
                                 Neurona fuente: """ + fuente + "\n\n"
                        + "Neuronas alcanzables: " + resultado.getAlcanzables().tamano() + "\n"
                        + resultado.getAlcanzables().toString() + "\n\n"
                        + "Neuronas inalcanzables: " + resultado.getInalcanzables().tamano() + "\n"
                        + resultado.getInalcanzables().toString() + "\n\n"
                        + "Red fuertemente conexa: "
                        + (resultado.esFuertementeConexa() ? "Sí" : "No");

                javax.swing.JOptionPane.showMessageDialog(this, mensaje, "Resultado DFS", javax.swing.JOptionPane.INFORMATION_MESSAGE);

            } catch (Exception e) { // Casos de error y registro en consola
                if (panelResultados != null) {
                    panelResultados.mostrarErrorValidacion("Error en DFS desde " + fuente + ": " + e.getMessage());
                }
                javax.swing.JOptionPane.showMessageDialog(this, "Error al ejecutar DFS: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_btnDFSActionPerformed

    private void btnDijkstraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDijkstraActionPerformed
        // TODO add your handling code here:
        
        // Se extrae el texto introducido en los TextField, aplicando .trim() al mismo tiempo
        String origen = txtDijkstraOrigen.getText().trim();
        String destino = txtDijkstraDestino.getText().trim();

        // Alertar al usuario sobre la introducción de datos inválidos (vacío)
        if (origen.isEmpty() || destino.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Por favor, ingresa origen y destino.",
                "Campos Vacíos",
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            // Procesamiento de datos enviados al método del controlador
            Ruta rutaResultante = controlador.calcularRuta(origen, destino);

            // Registro de la operación en la consola
            if (panelResultados != null) {
                panelResultados.mostrarRuta(rutaResultante);
            }

            // Comprobación de que la ruta existe
            if (rutaResultante.existeRuta()) {

                // Resaltar las líneas en el visualizador del grafo
                if (visualizadorGrafo != null) {
                    visualizadorGrafo.resaltarRuta(rutaResultante.getSecuenciaNeuronas());
                }

                // Formatear el texto usando el método toString() de la clase Ruta
                String mensaje = rutaResultante.toString();
                javax.swing.JOptionPane.showMessageDialog(this, mensaje, "Ruta Óptima", javax.swing.JOptionPane.INFORMATION_MESSAGE);

            } else {
                // Llamada al método getMensaje()de la clase Ruta
                javax.swing.JOptionPane.showMessageDialog(this, rutaResultante.getMensaje(), "Sin Ruta", javax.swing.JOptionPane.WARNING_MESSAGE);
            }

        } catch (Exception e) { // Se atrapan errores y se informa al usuario
            javax.swing.JOptionPane.showMessageDialog(this, "Error al calcular Dijkstra: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDijkstraActionPerformed

    private void btnFatigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFatigaActionPerformed
        // TODO add your handling code here:
        
        try {
            // Se llama al método para modificar el coeficiente k de las neuronas presentes en la red
            controlador.simularDeterioro();
            
            // Se registra la operación en la consola
            if (panelResultados != null) {
                panelResultados.registrarOperacionSistema("Se aplicó un ciclo de fatiga general. Coeficientes de transmisión K reducidos.");
            }
            
            // Se actualiza el visualizador del grafo
            if (visualizadorGrafo != null) {
                visualizadorGrafo.actualizarGrafo(controlador.getGrafo());
            }

            //Informe al usuario
            javax.swing.JOptionPane.showMessageDialog(this, "Ciclo de fatiga aplicado a toda la red. Coeficientes K actualizados.", "Fatiga Aplicada", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) { // Casos de error y alerta al usuario
            if (panelResultados != null) {
                panelResultados.mostrarErrorValidacion("Error al simular fatiga: " + e.getMessage());
            }
            javax.swing.JOptionPane.showMessageDialog(this, "Error al aplicar fatiga: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnFatigaActionPerformed

    private void btnTraumatismoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTraumatismoActionPerformed
        // TODO add your handling code here:
        
        // Se extrae el texto introducido en el TextField
        String idEliminar = txtTraumatismo.getText().trim();
    
        // Se informa al usuario si no se han introducido valores
        if (idEliminar.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ingresa el ID de la neurona a dañar.", "Campo Vacío", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Se solicita confirmación al usuario
        int confirmacion = javax.swing.JOptionPane.showConfirmDialog(this, "¿Estás seguro de que deseas eliminar la neurona " + idEliminar + "? Esta acción no se puede deshacer.", "Confirmar Traumatismo", javax.swing.JOptionPane.YES_NO_OPTION);
        
        // Se confirma la acción
        if (confirmacion == javax.swing.JOptionPane.YES_OPTION) {
            try {
                
                // Se llama al método para eliminar la neurona
                controlador.simularTraumatismo(idEliminar);
                
                // Registro de la operación en consola
                if (panelResultados != null) {
                    panelResultados.registrarOperacionSistema("TRAUMATISMO CRÍTICO: Se ha eliminado permanentemente la neurona con ID: " + idEliminar);
                }
                
                // Actualización del grafo
                if (visualizadorGrafo != null) {
                    visualizadorGrafo.actualizarGrafo(controlador.getGrafo());
                }

                // Informe de éxito
                javax.swing.JOptionPane.showMessageDialog(this, "Neurona " + idEliminar + " eliminada por traumatismo.", "Traumatismo Exitoso", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                txtTraumatismo.setText("");
                
            } catch (Exception e) { //Casos de error y alerta al usuario
                if (panelResultados != null) {
                    panelResultados.mostrarErrorValidacion("Fallo al intentar destruir neurona " + idEliminar + ": " + e.getMessage());
                }
                javax.swing.JOptionPane.showMessageDialog(this, "Error en el traumatismo: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnTraumatismoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBFS;
    private javax.swing.JButton btnCargarNeuro;
    private javax.swing.JButton btnCargarRed;
    private javax.swing.JButton btnDFS;
    private javax.swing.JButton btnDijkstra;
    private javax.swing.JButton btnFatiga;
    private javax.swing.JButton btnTraumatismo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblEstadoNeuro;
    private javax.swing.JLabel lblEstadoRed;
    private javax.swing.JTextField txtDijkstraDestino;
    private javax.swing.JTextField txtDijkstraOrigen;
    private javax.swing.JTextField txtNeuronaFuente;
    private javax.swing.JTextField txtTraumatismo;
    // End of variables declaration//GEN-END:variables
}
