/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package synapselogic;

/**
 * Consola de la interfaz donde se refleja una descripción de las acciones realizadas
 * @author Luis Velásquez
 */
@SuppressWarnings("serial")
public class PanelResultados extends javax.swing.JPanel {

    /**
     * Creates new form PanelResultados
     */
    public PanelResultados() {
        initComponents();
    }

    /**
     * Mostrar cualquier acción realizada por el sistema.
     * Ejemplo: Cargas de archivos, aplicación de fatiga, eliminación de neuronas.
     * @param accion realizada.
     */
    public void registrarOperacionSistema(String accion) {
        txtConsola.append(" OPERACIÓN DEL SISTEMA:\n");
        txtConsola.append("  " + accion + "\n");
        txtConsola.append("--------------------------------------------------\n");
        hacerScrollAlFinal();
    }

    /**
     * Mostrar errores y observaciones de validación en lenguaje comprensible.
     * @param mensajeError
     */
    public void mostrarErrorValidacion(String mensajeError) {
        txtConsola.append(" ERROR / VALIDACIÓN:\n");
        txtConsola.append("  " + mensajeError + "\n");
        txtConsola.append("--------------------------------------------------\n");
        hacerScrollAlFinal();
    }

    /**
     * Mostrar resultados de conectividad (Neuronas alcanzables/inalcanzables)
     * @param algoritmo
     * @param resultado
     */
    public void mostrarResultadosConectividad(String algoritmo, ResultadoConectividad resultado) {
        txtConsola.append(" ANÁLISIS DE CONECTIVIDAD (" + algoritmo + "):\n");
        
        // Se extraen los datos del colaborador ResultadoConectividad
        txtConsola.append("  Total alcanzables: " + resultado.getAlcanzables().tamano() + "\n");
        txtConsola.append("  ¿Red fuertemente conexa?: " + (resultado.esFuertementeConexa() ? "Sí" : "No") + "\n");
        txtConsola.append("--------------------------------------------------\n");
        hacerScrollAlFinal();
    }
    
    public void mostrarReporteCarga(String titulo, String reporte) {
    if (reporte == null || reporte.trim().isEmpty()) {
        return;
    }

    StringBuilder texto = new StringBuilder();

    texto.append("\n========================================\n");
    texto.append(titulo).append("\n");
    texto.append("========================================\n");
    texto.append(reporte).append("\n");

    txtConsola.append(texto.toString());
    txtConsola.setCaretPosition(txtConsola.getDocument().getLength());
}

    /**
     * Mostrar la ruta más rápida calculada y el costo total de transmisión.
     * @param ruta
     */
    public void mostrarRuta(Ruta ruta) {
        txtConsola.append(" CÁLCULO DE RUTA ÓPTIMA (DIJKSTRA):\n");
        
        if (ruta.existeRuta()) {
            // Uso del método toString() de la clase Ruta
            txtConsola.append(ruta.toString() + "\n");
        } else {
            txtConsola.append("  " + ruta.getMensaje() + "\n");
        }
        
        txtConsola.append("--------------------------------------------------\n");
        hacerScrollAlFinal();
    }


    /**
     * Método auxiliar privado para que la consola siempre baje automáticamente 
     * cuando se realiza una acción.
     */
    private void hacerScrollAlFinal() {
        javax.swing.SwingUtilities.invokeLater(() -> {
            txtConsola.setCaretPosition(txtConsola.getDocument().getLength());
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtConsola = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(33, 41, 36));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Panel de resultados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        setForeground(new java.awt.Color(33, 41, 36));

        txtConsola.setEditable(false);
        txtConsola.setBackground(new java.awt.Color(0, 0, 0));
        txtConsola.setColumns(20);
        txtConsola.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        txtConsola.setForeground(new java.awt.Color(4, 197, 17));
        txtConsola.setLineWrap(true);
        txtConsola.setRows(5);
        txtConsola.setText("\n");
        txtConsola.setWrapStyleWord(true);
        txtConsola.setMinimumSize(new java.awt.Dimension(130, 38));
        jScrollPane1.setViewportView(txtConsola);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtConsola;
    // End of variables declaration//GEN-END:variables
}
